<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CadProjector.Geometry\CadProjector.Geometry.csproj" />
    <ProjectReference Include="..\CadProjector.Core\CadProjector.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="IxMilia.Dxf" Version="0.8.4" />
    <PackageReference Include="Svg" Version="3.4.7" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
