<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CadProjector.Core\CadProjector.Core.csproj" />
    <ProjectReference Include="..\CadProjector.Geometry\CadProjector.Geometry.csproj" />
    <ProjectReference Include="..\CadProjector.Logging\CadProjector.Logging.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Encoding.CodePages" Version="10.0.11" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
